# This configuration file will make Travis CI do the following:
# - download the latest source
# - install the code
# - run unit and integration tests
# - compile our article PDF(s) and force-push them back to the repository

# The PDF compilation hack is by Dan Foreman-Mackey, with modifications by Andy Casey.

# Travis needs to be provided with the environment variables:
# - GITHUB_USER:    your GitHub username
# - GITHUB_API_KEY: a personal access token - make sure that it has access to
#                   'repo' - https://github.com/settings/tokens

# Remember to go to Travis settings and set to only build if .travis.yml is present

sudo: false
language: python

python:
  - 2.7
  - 3.5
  - 3.6

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  #- conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not
  # specific to using Miniconda.
  # (Note: I have commented these out because this repository is not using 
  #        multiprocessing in testing at the moment and if we can get away
  #        without using sudo then we can use Travis containers, which are
  #        way betterrer)
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm

install: 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose six coverage scikit-learn 
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then source .ci/setup-texlive.sh; fi

before_script: # configure a headless display to test plot generation
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
  - nosetests --with-coverage --cover-package=snob 
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then source .ci/travis.sh; fi
  
after_success:
  - coveralls

notifications:
  email:
    recipients:
      - andrew.casey@monash.edu 
    on_success: change
    on_failure: change

